version: '3.8'

services:
  schedulingapi:
    container_name: agendamento_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JwtSettings__Key=${JWT_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: agendamento_db
    environment:
      POSTGRES_USER: agendamento_user
      POSTGRES_PASSWORD: agendamento_password
      POSTGRES_DB: agendamento_db        
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d